name: Rost_Rodrigo_et_al_2016

dependencies:
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- cairo=1.12.18=6
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- decorator=4.0.10=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.43.0=1
- harfbuzz=0.9.39=1
- ipykernel=4.5.0=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jinja2=2.8=py27_1
- jsonschema=2.5.1=py27_0
- jupyter_client=4.4.0=py27_0
- jupyter_core=4.1.1=py27_0
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libxml2=2.9.2=0
- llvmlite=0.13.0=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.3=np111py27_0
- mistune=0.7.2=py27_0
- mkl=11.3.3=0
- nbconvert=4.2.0=py27_0
- nbformat=4.1.0=py27_0
- notebook=4.2.2=py27_0
- numba=0.28.1=np111py27_0
- numpy=1.11.1=py27_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- pango=1.39.0=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.3=py27_0
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.1.3=py27_0
- pymc=2.3.6=np111py27_2
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- pyzmq=15.4.0=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.18.0=np111py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.4.1=py27_0
- traitlets=4.3.0=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - iminuit==1.2
  - ipycache==0.1.4
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-core==4.1.1
  - probfit==1.0.5
  - prompt-toolkit==1.0.3
  - uncertainties==3.0.1
